### ISSUE TITLE
Create documentation for edgex-global-pipelines manual bump of stable and experimental tags

### ISSUE THREAD

**Issue by lranjbar** [edgexfoundry/edgex-global-pipelines#124]
Need to update the developer documentation on how to use the experimental tag and possibly avoid using the Jenkinsfile.sandbox

**Comment by jamesrgregg** [comment]
[US6202](https://rally1.rallydev.com/#/detail/userstory/371688703020?fdp=true): EdgeX DevOps: Documentation: edgex-global-pipelines manual bump of stable and experimental tags

**Comment by jamesrgregg** [comment]
This might best be achieved by a video recording published to the DevOps WG wiki vs formal documentation.
Will discuss within the DevOps WG.

**Comment by ernestojeda** [comment]
https://asciinema.org/a/gxtkk9fY04xZMvqreH298b1NP

**Comment by jamesrgregg** [comment]
sweet @ernestojeda !! thank you

**Comment by jamesrgregg** [comment]
# you must have write access to the repo to do this
$ git clone git@github.com:edgexfoundry/edgex-global-pipelines.git
$ cd edgex-global-pipelines
$ ./scripts/update-named-tag.sh <version> stable
