### ISSUE TITLE
Integrate edgeXSnap function into edgeXBuildGoApp and edgeXBuildCApp

### ISSUE THREAD

**Issue by lranjbar** [edgexfoundry/edgex-global-pipelines#125]
Add a stage to the edgeXBuildGoApp and edgeXBuildCApp to include building snaps in the pipelines.

- Need to add a when condition to check if the repository is snappable. Potentially just check if snapcraft.yaml exists in the repository.
- Snap job type should be "build" on PRs
- Snap job type should be "stage" on merge

**Comment by jamesrgregg** [comment]
[US6244](https://rally1.rallydev.com/#/detail/userstory/373747834492?fdp=true): EdgeX DevOps: Integrate edgeXSnap function into edgeXBuildGoApp and edgeXBuildCApp
