### ISSUE TITLE
Create global function to handle docker images for the automated release

### ISSUE THREAD

**Issue by lranjbar** [edgexfoundry/edgex-global-pipelines#135]
Add logic to edgeXReleaseDockerHub and edgeXReleaseDockerNexus.

- It might be possible to collapse these two functions into one function.
- Need to talk to the Linux foundation about releasing images to docker hub. See if there are any scripts the use internally.

For edgeXReleaseDockerNexus:
- We will re-tag the latest image for the release branch in docker.staging with the given version and push to docker.release.
- Pull latest image from docker.staging -> re tag with version -> push to docker.release in the Nexus

**Comment by jamesrgregg** [comment]
[US6131](https://rally1.rallydev.com/#/detail/userstory/367955863360?fdp=true): EdgeX DevOps: Create global function to handle docker images for the automated release
