### ISSUE TITLE
EdgeX Devops Investigate GO_PROXY usage in Go based Snap builds

### ISSUE THREAD

**Issue by jamesrgregg** [edgexfoundry/edgex-global-pipelines#160]
EdgeX Devops Investigate GO_PROXY usage in Go based Snap builds
With the use edgeXSnap, it is not clear id GO_PROXY is being used when building Go based snaps. The GO_PROXY env var should be set to https://nexus3.edgexfoundry.org/repository/go-proxy/

This is a SPIKE to investigate this for Hanoi scope.
[US6467](https://rally1.rallydev.com/#/detail/userstory/386146329424?fdp=true): EdgeX DevOps: EdgeX Devops Investigate GO_PROXY usage in Go based Snap builds

**Comment by tonyespy** [comment]
@jamesrgregg I did a bit of reading on this topic this morning. From what I gather, what we've done is  effectively setup a local cache on nexus of all the go package dependencies for our various repositories, correct? Also, from what I've read, the env var is GOPROXY not GO_PROXY?

As for supporting this in the snap, I think it would just be a matter of setting this environment variable from either the global snap function, as I don't think it makes sense to set it on a per-repository basis.

I can go ahead give this a try by modifying one of the snap's directly and will report my results in this issue.

**Comment by jamesrgregg** [comment]
Fixed in https://github.com/edgexfoundry/cd-management/pull/22
