### ISSUE TITLE
snap functions don't work well for local development/CI PR's

### ISSUE THREAD

**Issue by anonymouse64** [edgexfoundry/edgex-global-pipelines#182]
The snap functions currently for device-mqtt-go and device-modbus-go don't work well because the snapcraft.yaml there still has a VERSION file defined in the version-script, which means that in order to build the snap you need a VERSION file defined in the project tree when running snapcraft.

It seems that the snap functions here make this work successfully by auto-generating the VERSION file and thus snapcraft in the pipelines builds, but to do this, the VERSION file was deleted from the git repos. This deletion is problematic for the old jenkins jobs which apparently are still around (and I can't tell if the new pipelines jobs are running against PR's opened which change the snap files, but the old freestyle jobs definitely seem to be running as per https://github.com/edgexfoundry/device-mqtt-go/pull/145) as well as for local builds/development on the snap because the snap fails to build from source w/o a VERSION file present. 

I think the right thing to do here is either:
1) commit a dummy VERSION file which never changes to all the repos so that local snapcraft builds and PR jobs work
2) change the snapcraft.yaml version-script to not require VERSION, i.e. maybe if VERSION file is there in the case of pipelines use it, otherwise just hard-code that part of the version string to be "local" or "dirty" or something otherwise suggesting it is not being built as part of production CI

Thanks

**Comment by anonymouse64** [comment]
CC @lranjbar

**Comment by jamesrgregg** [comment]
[US6640](https://rally1.rallydev.com/#/detail/userstory/391895732980?fdp=true): EdgeX DevOps: Update snap scripts to not require local VERSION file
