### ISSUE TITLE
Update edgeXReleaseDocker to update labels

### ISSUE THREAD

**Issue by jamesrgregg** [edgexfoundry/edgex-global-pipelines#183]
EdgeX DevOps: Update edgeXReleaseDocker to update labels

[US6635](https://rally1.rallydev.com/#/detail/userstory/391611595592?fdp=true): EdgeX DevOps: Update edgeXReleaseDocker to update labels

**Comment by jamesrgregg** [comment]
[US6635](https://rally1.rallydev.com/#/detail/userstory/391611595592?fdp=true): EdgeX DevOps: Update edgeXReleaseDocker to update dlabels

**Comment by ernestojeda** [comment]
Closing. This will be handled by https://github.com/edgexfoundry/cd-management/issues/64.
