### ISSUE TITLE
EdgeX DevOps: edgeXReleaseSnap allows you to provide a snapRevision but not architecture

### ISSUE THREAD

**Issue by jamesrgregg** [edgexfoundry/edgex-global-pipelines#184]
EdgeX DevOps: edgeXReleaseSnap allows you to provide a snapRevision but not architecture

[US6637](https://rally1.rallydev.com/#/detail/userstory/391627475092?fdp=true): EdgeX DevOps: edgeXReleaseSnap allows you to provide a snapRevision but not architecture

**Comment by ernestojeda** [comment]
Closing as Canonical is taking over Snap publishing.
