### ISSUE TITLE
When the edgeXReleaseSnap promotes a snap revision it keeps the previous tag on the snap. Need to look into if there is a way to retag the snap.

### ISSUE THREAD

**Issue by jamesrgregg** [edgexfoundry/edgex-global-pipelines#185]
- Per DevOps WG 5/14/20 - look into repacking snap to achieve th
 - Unpack snap
 - Update version in snapcraft.yaml 
 - repack snap
 - push to snap store (edge) ?

**Comment by jamesrgregg** [comment]
[US6636](https://rally1.rallydev.com/#/detail/userstory/391627458920?fdp=true): EdgeX DevOps: Update edgeXReleaseSnap to update the tag of the snap

**Comment by ernestojeda** [comment]
Closing as Canonical is taking over snap publishing.
