### ISSUE TITLE
EdgeX DevOps: Implementation of the docker image promotion techniques (edgexBuild*) pipelines

### ISSUE THREAD

**Issue by jamesrgregg** [edgexfoundry/edgex-global-pipelines#189]
EdgeX DevOps: Implementation of the docker image promotion techniques (edgexBuild*) pipelines

Implement edgeXDocker.promote in edgeXBuildGoApp and edgeXBuildCApp and edgeXBuildDocker

[US6789](https://rally1.rallydev.com/#/detail/userstory/396197197672?fdp=true): EdgeX DevOps: Implementation of the docker image promotion techniques (edgexBuild*) pipelines

**Comment by ernestojeda** [comment]
This will not possible. Closing.
