### ISSUE TITLE
Documentation: Process flow diagram on image promotion process which will stream line build automation

### ISSUE THREAD

**Issue by jamesrgregg** [edgexfoundry/edgex-global-pipelines#193]
Documentation: Process flow diagram on image promotion process which will stream line build automation

**Comment by jamesrgregg** [comment]
[US6834](https://rally1.rallydev.com/#/detail/userstory/397604096580?fdp=true): EdgeX DevOps: Documentation: Process flow diagram on image promotion process which will stream line build automation

**Comment by ernestojeda** [comment]
Closing. Image promotion not in scope anymore due to technical issues.
