### ISSUE TITLE
EdgeX DevOps: figure out how to unit test Jenkins declaritive pipeline code and integrate it into the edgex-global-pipelines build automation process

### ISSUE THREAD

**Issue by jamesrgregg** [edgexfoundry/edgex-global-pipelines#194]
EdgeX DevOps: figure out how to unit test Jenkins declaritive pipeline code and integrate it into the edgex-global-pipelines build automation process

[US5855](https://rally1.rallydev.com/#/detail/userstory/355501442268?fdp=true): EdgeX DevOps: figure out how to unit test Jenkins declaritive pipeline code and integrate it into the edgex-global-pipelines build automation process

**Comment by ernestojeda** [comment]
I am not sure this is worth the effort. Functional testing is probably the best route for this.
