### ISSUE TITLE
EdgeX DevOps: Spike research auto-generation of documentation for edgex-global-pipelines

### ISSUE THREAD

**Issue by jamesrgregg** [edgexfoundry/edgex-global-pipelines#195]
EdgeX DevOps: Spike research auto-generation of documentation for edgex-global-pipelines

Research Groovy native and generic ways to auto-generate documentation. Also include some examples on how to use the pipelines

[US6203](https://rally1.rallydev.com/#/detail/userstory/371688709472?fdp=true): EdgeX DevOps: Spike research auto-generation of documentation for edgex-global-pipelines

**Comment by jamesrgregg** [comment]
https://www.javaworld.com/article/2074120/documenting-groovy-with-groovydoc.html

https://docs.groovy-lang.org/latest/html/documentation/

https://stackoverflow.com/questions/44823071/how-to-generate-groovydoc-from-jenkins-global-library

**Comment by ernestojeda** [comment]
We landed on a custom solution to parse comments out of the source code and generate markdown files. Then that markdown is stored in a separate branch and mkdocs is used to generate HTML from that markdown.
