### ISSUE TITLE
EdgeX DevOps: Build Snaps natively on Ubuntu.

### ISSUE THREAD

**Issue by ernestojeda** [edgexfoundry/edgex-global-pipelines#252]
Remove docker support for building snaps and build natively on Ubuntu OS.

**Comment by ernestojeda** [comment]
See comment from this PR: https://github.com/edgexfoundry/ci-management/pull/629#issuecomment-699052405

**Comment by siggiskulason** [comment]
@ernestojeda I checked a build script into https://github.com/siggiskulason/ci-management/blob/snap-build-snap-script/shell/build-snap.sh - It's a simple bash script which installs the prerequisites and builds a snap on Ubuntu. Is this all you need?

**Comment by ernestojeda** [comment]
Yes. I will add this to edgex-global-pipelines

**Comment by jamesrgregg** [comment]
[US7394](https://rally1.rallydev.com/#/detail/userstory/443171744828?fdp=true): EdgeX DevOps: Build Snaps natively on Ubuntu

**Comment by jamesrgregg** [comment]
Plan to continue testing scripts in Sprint 63.

**Comment by ernestojeda** [comment]
Closing...Canonical has taken over this with GitHub actions
