### ISSUE TITLE
EdgeX DevOps: Dockerfile clean up in some services

### ISSUE THREAD

**Issue by jamesrgregg** [edgexfoundry/edgex-global-pipelines#302]
👕 - Medium
    Consistency; adhere to best practices for security (linter) – DevOps (medium in size)
    Is a linter required in the pipeline? This may affect developer flow.
[US7548](https://rally1.rallydev.com/#/detail/userstory/459137102508?fdp=true): EdgeX DevOps: Dockerfile clean up in some services

**Comment by ernestojeda** [comment]
No linter required for initial implementation. Based on architects meeting yesterday the decision is:

- Move to alpine 3.12 (in second stage from in Dockerfile)
- For build stage, we will use Go 1.15 with 3.12 Alpine where applicable (for Go services)

Separate issues will be created for:
- Other Dockerfile consistency issues (for best practices) – such as common use of `apk add --update --no-cache` when doing package installs.
