### ISSUE TITLE
Set up codecov for edgex-global-pipelines

### ISSUE THREAD

**Issue by lranjbar** [edgexfoundry/edgex-global-pipelines#56]
After the unit testing spike see if it is possible to set up codecov for this repository as well.

**Comment by jamesrgregg** [comment]
We did the spike on this and although it's possible, we will not do this for Geneva.  This could be considered for a future release

**Comment by jamesrgregg** [comment]
[US6424](https://rally1.rallydev.com/#/detail/userstory/381637397396?fdp=true): EdgeX DevOps: Add codecov/ coverage report to edgex-global-piplines
