### ISSUE TITLE
Look for a bot to replace "recheck"

### ISSUE THREAD

**Issue by ernestojeda** [edgexfoundry/edgex-global-pipelines#87]

**Comment by ernestojeda** [comment]
US5959

**Comment by jamesrgregg** [comment]
this needs to be a spike to work offline in the upcoming sprint

- dedicated build service account needed
- whitelist component
- PAT needed

**Comment by jamesrgregg** [comment]
Alternative options now being considered using Jenkins plugin
https://plugins.jenkins.io/github-pr-comment-build

**Comment by vishwassp-hcl-intel** [comment]
The right plugin is: 
https://plugins.jenkins.io/pipeline-github/

**Comment by jamesrgregg** [comment]
implemented and working in LF Jenkins infrastructure
